export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'
export const SELECT_ARTICLE = 'SELECT_ARTICLE'
export const SELECT_DATE = 'SELECT_DATE'
export const ADD_COMMENT = 'ADD_COMMENT'
export const LOAD_ALL_ARTICLES = 'LOAD_ALL_ARTICLES'